### PR TITLE
Fix viewattendance command and parser bugs

### LINKED ISSUE #176: [PE-D][Tester E] Incorrect result when using "viewattendance" when the full name of student is used
The command, "viewattendance", does not work as intended if I use the full name of the student. In the first screenshot, when using "David Li", the sessions shown will include a session that does not David did not attend. 
(By the way, the app clears the command that was inputed after execution but I have placed the exact command I have keyed in for easy reference:)) 

The command works find when using the name "David".

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zannloo/ped#4

### LINKED ISSUE #206: [PE-D][Tester A] Integration Test - View Attendance Not Working As Expected
David Li has been marked as absent for sessions 1 and 2. However, when I list attendance, I see the message "2 sessions listed!". 
Correct output should be: "No session listed" or "Zero sessions listed" and David Li was absent for both.

Try out these set of commands:

`takeattendance n/David Li s/1 ap/absent`

`takeattendance n/David Li s/2 ap/absent`

`viewattendance n/David Li`

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: AlagappanRa/ped#9

### PR DESCRIPTION
**Pull request by ldinghan**

### CODE REVIEW

File: src/main/java/seedu/address/Main.java [hunk 1]
```diff
@@ -13,7 +13,6 @@
  *
  *     Error: JavaFX runtime components are missing, and are required to run this application
  *
- * The reason is that MainApp extends Application. In that case, the
```
Comment (raydenlim) [inline src/main/java/seedu/address/Main.java:16]: is this deletion by accident? haha

File: src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java [hunk 2]
```diff
@@ -47,6 +54,20 @@ public ViewAttendanceCommand(Predicate<Session> predicate) {
...
+        try {
+            if (!names.isEmpty()) {
+                Set<Person> students = new HashSet<>();
+                for (Name name : names) {
+                    students.add(model.getMatchingStudentName(name));
+                }
+                predicate = new SessionStudentsContainsKeywordsPredicate(students);
+            }
+        } catch (PersonNotFoundException e) {
+            throw new CommandException(Messages.MESSAGE_PERSON_NOT_FOUND);
```
Comment (raydenlim) [inline src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java:67]: Add a testcase to ensure an error is thrown

File: src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java [hunk 3]
```diff
@@ -25,15 +32,15 @@ public class ViewAttendanceCommand extends Command {
...
     public static final CommandType COMMAND_TYPE = CommandType.VIEW_ATTENDANCE;
 
-    private final Predicate<Session> predicate;
+    private final Set<Name> names;
 
     /**
      * Creates a `ViewAttendanceCommand` to view attendance of student(s) listed.
      *
-     * @param predicate The names of the student(s).
+     * @param names The names of the student(s).
```
Comment (raydenlim) [inline src/main/java/seedu/address/logic/commands/ViewAttendanceCommand.java]: "A set containing the names of the student(s)"

File: src/main/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicate.java [hunk 4]
```diff
@@ -1,35 +1,32 @@
 package seedu.address.model.session;
```
Comment (raydenlim) [inline src/main/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicate.java]: might want to refactor the name of this class, since there is no longer the `keyword`

File: src/test/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicateTest.java [hunk 5]
```diff
@@ -16,22 +17,25 @@
 import seedu.address.testutil.TypicalPersons;
 
 public class SessionStudentsContainsKeywordsPredicateTest {
```
Comment (raydenlim) [inline src/test/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicateTest.java]: same thing here, might want to change the class name

**Review by raydenlim — APPROVED** [review]
No jarring issues spotted. LGTM!

File: src/main/java/seedu/address/Main.java (hunk 1 above)
Comment (ldinghan) [reply src/main/java/seedu/address/Main.java:16]: Yup, nice catch!

Comment (ldinghan) [reply src/main/java/seedu/address/Main.java:16]: Yup nice catch!

File: src/main/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicate.java (hunk 4 above)
Comment (ldinghan) [reply src/main/java/seedu/address/model/session/SessionStudentsContainsKeywordsPredicate.java]: youre right
