### PR TITLE
Fix assignment list not appearing

### LINKED ISSUE #182: [PE-D][Tester D] viewassignments not working bug
viewassignments does not bring the gui to the assignments page. Even if you are in the assignments page, viewassignments does not show any details about the assignments besides the assignment names

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: samuelmui8/ped#6

### LINKED ISSUE #185: [PE-D][Tester D] editgrade not working bug
editgrade has no effect on the assignment details, the success message is shown but the changes are not reflected in the GUI.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: samuelmui8/ped#7

### LINKED ISSUE #189: [PE-D][Tester D] editcomment not working bug
editcomment has no effect on assignment details as well, the changes are not reflected on the GUI despite having a success message.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: samuelmui8/ped#8

### LINKED ISSUE #199: [PE-D][Tester C] Broken commands
View assignments command does not work at all

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Jonyxzx/ped#10

### LINKED ISSUE #207: [PE-D][Tester A] Integration Test - View Assignment does not work as expected
Load fresh initial state of the application, delete all related data files. Then type: 

`viewassignments 1`

`editgrade 1 as/Functional Expressionism g/500`

`viewassignments 1`

These bunch of commands give this output: 

Expected behaviour: I should be able to continue seeing the bunch of assignments that Alex Yeoh originally had. 

Current behaviour: [Refer to the screenshot]

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: AlagappanRa/ped#10

### LINKED ISSUE #208: [PE-D][Tester A] Missing Critical Functionality - There is no way for a CS1101S Avenger to add an assignment for a new incoming student.
I am only able to `viewassignments` for those students within the application, but not the students that I have added myself during the bug testing phase. The add command does not accept any argument that allows an Avenger to add an assignment for a particular student or even edit it in.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: AlagappanRa/ped#11

### PR DESCRIPTION
**Pull request by Originalidk**
Make viewassigments work after applying other commands.

### CODE REVIEW

**Review by raydenlim — APPROVED** [review]
LGTM! 
Looks sick

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -276,15 +291,11 @@ private CommandResult executeCommand(String commandText) throws CommandException
...
                 selectTab(TAB_TASKS_INDEX);
                 clearGraphicalResultDisplay();
                 break;
-            // Assignments
-            case DELETE_COMMENT:
-            case DELETE_GRADE:
-            case EDIT_COMMENT:
-            case EDIT_GRADE:
             case EDIT_GRADED_TEST:
                 selectTab(TAB_ASSIGNMENTS_INDEX);
```
Comment (raydenlim) [inline src/main/java/seedu/address/ui/MainWindow.java]: Change this to TAB_PERSONS_INDEX

**Review by raydenlim — APPROVED** [review]
