### PR TITLE
Fix too many prefix for viewtasks bug

### LINKED ISSUE #133: Add error message to tell user that only one prefix allowed for viewtasks

### PR DESCRIPTION
**Pull request by Respirayson**

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ViewTasksCommandParser.java [hunk 1]
```diff
@@ -38,6 +39,10 @@ public ViewTasksCommand parse(String args) throws ParseException {
         argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_TASK_NAME, PREFIX_TASK_DESCRIPTION,
                 PREFIX_TASK_PRIORITY, PREFIX_TASK_PROGRESS, PREFIX_DATE);
 
+        if (argMultimap.getCountOfPrefixes() > 2) {
+            throw new ParseException(MESSAGE_MANY_PREFIXES);
```
Comment (raydenlim) [inline src/main/java/seedu/address/logic/parser/ViewTasksCommandParser.java:43]: add a test case here

**Review by raydenlim — COMMENTED** [review]
LGTM

**Review by raydenlim — APPROVED** [review]
LGTM. No significant errors
